### PR TITLE
Patch BranchProtection state migration

### LINKED ISSUE #586: [panic] State migration of BranchProtection from v5 -> v6 fails
### What happened?

When upgrading this package from v5 to v6, we get a panic on the `BranchProtection` resource. On v5, the properties `blocksCreations` and `pushRestrictions` are migrated to a nested object within the `restrictPushes` list property on v6.

Stack:

```
Diagnostics:
  github:index:BranchProtection (test-repo-branch-protection-panic-protection):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (4811-ringo):
    panic: interface conversion: interface {} is nil, not bool
    goroutine 84 [running]:
    github.com/integrations/terraform-provider-github/v6/github.resourceGithubBranchProtectionUpgradeV1({0x1?, 0x103a7d530?}, 0x0?, {0x2?, 0x14000112b00?})
        /home/runner/go/pkg/mod/github.com/integrations/terraform-provider-github/v6@v6.0.0/github/migrate_github_branch_protection.go:67 +0x244
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.UpgradeJSONState({0x103a7d290, 0x104585320}, 0x1?, 0x1400050c480?, 0x140001efce0?, {0x103773060, 0x140002b6940})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240202163305-e2a20ae13ef9/helper/schema/grpc_provider.go:485 +0x7c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.upgradeResourceState(0x1400010c900, 0x140004b3530?, 0x1400040cf70)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.74.0/pkg/tfshim/sdk-v2/upgrade_state.go:45 +0x1b4
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x1400010c900?, {0x0?, 0x103a7d300?, 0x1400081ec30?}}, {0x103a7d300, 0x1400081ec30}, {0x1034b702c, 0x18}, {0x103a7d9a0?, 0x14000828450}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.74.0/pkg/tfshim/sdk-v2/provider_diff.go:69 +0x188
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0x140004ab980, {0x103a7d300?, 0x1400081e7e0?}, 0x140003ee300)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.74.0/pkg/tfbridge/provider.go:883 +0x730
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x103a7d300, 0x1400081e7e0}, {0x1039aac80?, 0x140003ee300})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/proto/go/provider_grpc.pb.go:575 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x103a7d300, 0x1400081e240}, {0x1039aac80, 0x140003ee300}, 0x1400048e0a0, 0x140004368d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x103a2ad40?, 0x140004ab980}, {0x103a7d300, 0x1400081e240}, 0x140003ee280, 0x14000128380)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/proto/go/provider_grpc.pb.go:577 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140003e8600, {0x103a7d300, 0x1400081e1b0}, {0x103a86280, 0x1400018e4e0}, 0x14000806360, 0x1400074a5d0, 0x10453f168, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1385 +0xb8c
    google.golang.org/grpc.(*Server).handleStream(0x140003e8600, {0x103a86280, 0x1400018e4e0}, 0x14000806360)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1796 +0xc4c
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1029 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1040 +0x150
```

### Example

Create a new repo in a Github organization (not individual user account). Then setup a new Pulumi project with `@pulumi/github@v5.26.0`:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as github from "@pulumi/github";

// pulumi config set repository <name-of-existing-test-repository>
const config = new pulumi.Config();
const testRepo = config.require<string>('repository');

// pulumi config set github:owner <owner>
const ghConfig = new pulumi.Config('github');
const ghOrg = ghConfig.require<string>('owner')

const testRepository = github.getRepositoryOutput({
    fullName: `${ghOrg}/${testRepo}`,
});

// v5
const protection = new github.BranchProtection(
    `${testRepo}-protection`,
    {
        repositoryId: testRepository.id,
        pattern: 'main',
        enforceAdmins: true,
        allowsDeletions: false,
        requiredPullRequestReviews: [
            {
                dismissStaleReviews: true,
                requiredApprovingReviewCount: 1,
            },
        ],

        pushRestrictions: [
            "/ringods"
        ]
    },
    {
        deleteBeforeReplace: true,
    },
);

// v6
// const protection = new github.BranchProtection(
//     `${testRepo}-protection`,
//     {
//         repositoryId: testRepository.id,
//         pattern: 'main',
//         enforceAdmins: true,
//         allowsDeletions: false,
//         requiredPullRequestReviews: [
//             {
//                 dismissStaleReviews: true,
//                 requiredApprovingReviewCount: 1,
//             },
//         ],

//         restrictPushes: [
//             {
//                 pushAllowances: [
//                     "/ringods"
//                 ]
//             }
//         ]
//     },
//     {
//         deleteBeforeReplace: true,
//     },
// );
```

Run `pulumi up`.

Change `@pulumi/github` to `v6.0.0` in your `package.json` and run `npm install`. Now comment the `v5` block and uncomment the `v6` block.

Run `pulumi up` again to see the panic appear.

### Output of `pulumi about`

```
CLI          
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
github  6.0.0
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/ringods/.volta/bin/node' version='v18.15.0'

Current Stack: team-ce/4811/ringo

TYPE                                            URN
pulumi:pulumi:Stack                             urn:pulumi:ringo::4811::pulumi:pulumi:Stack::4811-ringo
pulumi:providers:github                         urn:pulumi:ringo::4811::pulumi:providers:github::default_5_26_0
github:index/branchProtection:BranchProtection  urn:pulumi:ringo::4811::github:index/branchProtection:BranchProtection::test-repo-branch-protection-panic-protection


Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-ringo-pulumi-corp
User           v-ringo-pulumi-corp
Organizations  v-ringo-pulumi-corp, team-ce, ediri, demo, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/github  6.0.0
@pulumi/pulumi  3.108.1
@types/node     18.19.21

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default
```

### Additional context

I did a similar setup from v5 to v6 purely with Terraform but it works there, so I think this is an issue purely in this package.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #586

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
LGTM

File: provider/provider_test.go [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+
+	"github.com/pulumi/providertest/replay"
+	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge"
+	pulumirpc "github.com/pulumi/pulumi/sdk/v3/proto/go"
+
+	github "github.com/pulumi/pulumi-github/provider/v6"
+	"github.com/pulumi/pulumi-github/provider/v6/pkg/version"
+)
+
+const repro586 = `[
```
Comment (t0yv0) [inline provider/provider_test.go:15]: Could be adventurous and actually use provdertest upgrade tests here :) But this works.

Comment (iwahbe) [reply provider/provider_test.go:15]: I'll do that next time.
